def getCountryFlag(country):
    match country:
        case 'catar':
            return 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg'
        case 'equador':
            return 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg'
        case 'senegal':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg'
        case 'paises_baixos':
            return 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg'
        case 'inglaterra':
            return 'https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_England.svg'
        case 'ira':
            return 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg'
        case 'estados_unidos':
            return 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_the_United_States.svg'
        case 'pais_de_gales':
            return 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Flag_of_Wales.svg'
        case 'argentina':
            return 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg'
        case 'arabia_saudita':
            return 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg'
        case 'mexico':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg'
        case 'polonia':
            return 'https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_Poland.svg'
        case 'franca':
            return 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg'
        case 'australia':
            return 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg'
        case 'dinamarca':
            return 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg'
        case 'tunisia':
            return 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg'
        case 'espanha':
            return 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg'
        case 'costa_rica':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg'
        case 'alemanha':
            return 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg'
        case 'japao':
            return 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg'
        case 'belgica':
            return 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg'
        case 'canada':
            return 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg'
        case 'marrocos':
            return 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg'
        case 'croacia':
            return 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg'
        case 'brasil':
            return 'https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg'
        case 'servia':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg'
        case 'suica':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg'
        case 'camaroes':
            return 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg'
        case 'portugal':
            return 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg'
        case 'gana':
            return 'https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg'
        case 'uruguai':
            return 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg'
        case 'coreia_do_sul':
            return 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg'