countries = [
    "Catar",
    "Equador",
    "Senegal",
    "Holanda",
    "Inglaterra",
    "Irã",
    "Estados Unidos",
    "País de Gales",
    "Argentina",
    "Arábia Saudita",
    "México",
    "Polônia",
    "França",
    "Austrália",
    "Dinamarca",
    "Tunisia",
    "Espanha",
    "Costa Rica",
    "Alemanha",
    "Japão",
    "Bélgica",
    "Canáda",
    "Marrocos",
    "Croácia",
    "Brasil",
    "Sérvia",
    "Súiça",
    "Camarões",
    "Portugal",
    "Gana",
    "Uruguai",
    "Coréia do Sul"
]

